events {}

http {

    # =============================================
    # Redirection HTTP → HTTPS
    # =============================================
    server {
        listen 80;
        server_name pi-smart-parking.tail739c06.ts.net;
        return 301 https://$host$request_uri;
    }

    # =============================================
    # Application Web (port 443 → webapp:3000)
    # =============================================
    server {
        listen 443 ssl;
        server_name pi-smart-parking.tail739c06.ts.net;

        ssl_certificate     /etc/nginx/certs/pi-smart-parking.tail739c06.ts.net.crt;
        ssl_certificate_key /etc/nginx/certs/pi-smart-parking.tail739c06.ts.net.key;

        location / {
            proxy_pass http://webapp:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # =============================================
    # ChirpStack (port 8443 → chirpstack:8080)
    # =============================================
    server {
        listen 8443 ssl;
        server_name pi-smart-parking.tail739c06.ts.net;

        ssl_certificate     /etc/nginx/certs/pi-smart-parking.tail739c06.ts.net.crt;
        ssl_certificate_key /etc/nginx/certs/pi-smart-parking.tail739c06.ts.net.key;

        location / {
            proxy_pass http://chirpstack:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # =============================================
    # pgAdmin (port 5443 → pgadmin:80)
    # =============================================
    server {
        listen 5443 ssl;
        server_name pi-smart-parking.tail739c06.ts.net;

        ssl_certificate     /etc/nginx/certs/pi-smart-parking.tail739c06.ts.net.crt;
        ssl_certificate_key /etc/nginx/certs/pi-smart-parking.tail739c06.ts.net.key;

        location / {
            proxy_pass http://pgadmin:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # =============================================
    # Portainer (port 9443 → portainer:9000)
    # =============================================
    server {
        listen 9443 ssl;
        server_name pi-smart-parking.tail739c06.ts.net;

        ssl_certificate     /etc/nginx/certs/pi-smart-parking.tail739c06.ts.net.crt;
        ssl_certificate_key /etc/nginx/certs/pi-smart-parking.tail739c06.ts.net.key;

        location / {
            proxy_pass http://portainer:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
