- Development:
    - GitHub:
        href: https://github.com/

    - Documentation ChirpStack:
        href: https://www.chirpstack.io/docs/

    - Docker Docs:
        href: https://docs.docker.com/