title: Smart Parking CREPS
description: Tableau de bord Smart Parking IoT
theme: dark
color: slate

allowedHosts: "*"

layout:
  Smart Parking:
    style: row
    columns: 2

  Infrastructure:
    style: row
    columns: 3

  Database:
    style: row
    columns: 2