# ===========================================
# Configuration Mosquitto - Smart Parking
# ===========================================

# Port d'écoute MQTT standard
listener 1883
allow_anonymous true

# Port WebSocket (pour futures applis web temps réel)
listener 9001
protocol websockets
allow_anonymous true

# Persistance des messages
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true

# Limites de connexion
max_connections 200
max_keepalive 300

# Messages retenus (retained)
retain_available true

# QoS maximum supporté
# 0 = au plus une fois
# 1 = au moins une fois  
# 2 = exactement une fois
max_qos 2