- Applications:
    - ChirpStack:
        href: http://{{HOMEPAGE_VAR_IP}}:8080
        target: _blank
        description: "100.118.69.115:8080 • LoRaWAN Server • Identifiant: admin - MDP: Password123"
        icon: mdi-radio-tower
        container: smart-parking_chirpstack

    - pgAdmin:
        href: http://{{HOMEPAGE_VAR_IP}}:5050
        target: _blank
        description: "100.118.69.115:5050 • Interface BDD • Identifiant: admin@smartparking.com - MDP: Password123"
        icon: mdi-database-cog
        container: smart-parking_pgadmin

    - Portainer:
        href: http://{{HOMEPAGE_VAR_IP}}:9000
        target: _blank
        description: "100.118.69.115:9000 • Gestion Docker • Identifiant: admin - MDP: Password1234"
        icon: mdi-docker
        container: smart-parking_portainer

    - Homepage:
        href: http://{{HOMEPAGE_VAR_IP}}:3000
        target: _blank
        description: "100.118.69.115:3000 • Dashboard Applications"
        icon: mdi-view-dashboard
        container: smart-parking_homepage

- Smart Parking Serveur:
    - Gateway Bridge:
        description: "UDP 100.118.69.115:1700 • LoRa Gateway Bridge"
        icon: mdi-access-point
        container: smart-parking_gwbridge

    - MQTT:
        description: "100.118.69.115:1883 • Mosquitto Broker"
        icon: mdi-connection
        container: smart-parking_mqtt

    - Redis:
        description: "100.118.69.115:6379 • Cache Server"
        icon: mdi-memory
        container: smart-parking_redis

- Database:
    - PostgreSQL:
        description: "100.118.69.115:5432 • BDD PostgreSQL"
        icon: mdi-database
        container: smart-parking_db