---
- Applications :
    - ChirpStack:
        href: http://pi-smart-parking:8080
        target: _blank
        description: LoRaWAN Server
        icon: mdi-radio-tower
        container: smart-parking_chirpstack

    - pgAdmin:
        href: http://pi-smart-parking:5050
        description: "pi-smart-parking:5050 • Interface BDD • Identifiant: admin@smartparking.com - MPD: Password123"
        icon: mdi-database-cog
        container: smart-parking_pgadmin

    - Portainer:
        href: http://pi-smart-parking:9000
        description: "pi-smart-parking:9000 • Gestion Docker • Identifiant: admin - MPD: Password1234"
        icon: mdi-docker
        container: smart-parking_portainer

    - Homepage:
        href: http://pi-smart-parking:3000
        description: "pi-smart-parking:3000 • Dashboard Applications • Identifiant: admin - MPD: Password123"
        icon: mdi-view-dashboard
        container: smart-parking_homepage

- Smart Parking Serveur:
    - Gateway Bridge:
        description: "UDP pi-smart-parking:1700 • LoRa Gateway Bridge"
        icon: mdi-access-point
        container: smart-parking_gwbridge

    - MQTT:
        description: "pi-smart-parking:1883 • Mosquitto broker"
        icon: mdi-connection
        container: smart-parking_mqtt

    - Redis:
        description: "pi-smart-parking:6379 • Cache server"
        icon: mdi-memory
        container: smart-parking_redis

- Database:
    - PostgreSQL:
        description: "pi-smart-parking:5432 • BDD PostgreSQL"
        icon: mdi-database
        container: smart-parking_db
